spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_report
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

chronos.classification.default-country-code=TN